import fs from 'fs';
import path from 'path';

// Generate HTML file
const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chess Game UI</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="game-container">
        <div class="game-header">
            <h1>Chess Game</h1>
            <div class="game-info">
                <div class="current-turn">
                    <span class="label">Current Turn:</span>
                    <span id="currentTurn" class="value white">White</span>
                </div>
                <div class="game-status">
                    <span class="label">Status:</span>
                    <span id="gameStatus" class="value">Active</span>
                </div>
            </div>
        </div>

        <div class="game-content">
            <!-- Chessboard -->
            <div class="board-section">
                <div id="chessboard" class="chessboard">
                    <!-- Board will be generated by JavaScript -->
                </div>
                <div class="board-coordinates">
                    <div class="files">
                        <span>a</span><span>b</span><span>c</span><span>d</span>
                        <span>e</span><span>f</span><span>g</span><span>h</span>
                    </div>
                    <div class="ranks">
                        <span>8</span><span>7</span><span>6</span><span>5</span>
                        <span>4</span><span>3</span><span>2</span><span>1</span>
                    </div>
                </div>
            </div>

            <!-- Side Panel -->
            <div class="side-panel">
                <!-- Captured Pieces -->
                <div class="captured-section">
                    <h3>Captured Pieces</h3>
                    <div class="captured-pieces">
                        <div class="captured-white">
                            <div class="captured-label">Black Captured:</div>
                            <div id="capturedWhite" class="pieces-list"></div>
                        </div>
                        <div class="captured-black">
                            <div class="captured-label">White Captured:</div>
                            <div id="capturedBlack" class="pieces-list"></div>
                        </div>
                    </div>
                </div>

                <!-- Move History -->
                <div class="history-section">
                    <h3>Move History</h3>
                    <div id="moveHistory" class="move-history-list">
                        <p class="empty-message">No moves yet</p>
                    </div>
                </div>

                <!-- Game Controls -->
                <div class="controls-section">
                    <button id="undoBtn" class="btn btn-undo" disabled>↶ Undo</button>
                    <button id="restartBtn" class="btn btn-restart">⟲ Restart</button>
                    <button id="resetBtn" class="btn btn-reset">Reset Board</button>
                </div>
            </div>
        </div>

        <!-- Selection Info -->
        <div id="selectionInfo" class="selection-info">
            <p id="selectionText">Click a piece to select it</p>
        </div>

        <!-- Move Validation Message -->
        <div id="validationMessage" class="validation-message"></div>
    </div>

    <script src="game.js"></script>
</body>
</html>
`;

// Generate CSS file
const cssContent = `* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    min-height: 100vh;
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 20px;
}

.game-container {
    background: white;
    border-radius: 12px;
    box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
    max-width: 1200px;
    width: 100%;
}

.game-header {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
    padding: 20px;
    border-radius: 12px 12px 0 0;
    text-align: center;
}

.game-header h1 {
    font-size: 28px;
    margin-bottom: 15px;
    font-weight: 600;
}

.game-info {
    display: flex;
    justify-content: center;
    gap: 40px;
    flex-wrap: wrap;
}

.game-info > div {
    display: flex;
    align-items: center;
    gap: 10px;
}

.game-info .label {
    font-size: 14px;
    opacity: 0.9;
}

.game-info .value {
    font-size: 16px;
    font-weight: 600;
    padding: 4px 12px;
    border-radius: 4px;
    background: rgba(255, 255, 255, 0.2);
}

.game-info .value.white {
    background: rgba(255, 255, 255, 0.3);
}

.game-info .value.black {
    background: rgba(0, 0, 0, 0.2);
}

.game-content {
    display: flex;
    padding: 30px;
    gap: 30px;
    flex-wrap: wrap;
}

.board-section {
    flex: 1;
    min-width: 300px;
    display: flex;
    flex-direction: column;
    gap: 15px;
}

.chessboard {
    display: grid;
    grid-template-columns: repeat(8, 1fr);
    grid-template-rows: repeat(8, 1fr);
    gap: 0;
    aspect-ratio: 1;
    background: #8b7355;
    border: 3px solid #5d4037;
    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);
    max-width: 600px;
    width: 100%;
}

.square {
    aspect-ratio: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    cursor: pointer;
    position: relative;
    user-select: none;
    transition: all 0.2s ease;
    font-size: 3em;
    font-weight: bold;
}

.square.light {
    background: #f0d9b5;
}

.square.dark {
    background: #b58863;
}

.square.selected {
    box-shadow: inset 0 0 10px rgba(0, 0, 0, 0.4);
    background: #bcb365 !important;
}

.square.valid-move {
    box-shadow: inset 0 0 0 3px rgba(100, 200, 100, 0.6);
}

.square.invalid-move {
    box-shadow: inset 0 0 0 3px rgba(200, 100, 100, 0.6);
}

.square.hover:not(.empty) {
    transform: scale(0.95);
}

.square.dragging {
    opacity: 0.5;
}

.piece {
    cursor: grab;
    user-select: none;
    transition: all 0.1s ease;
}

.piece:active {
    cursor: grabbing;
}

.board-coordinates {
    display: grid;
    grid-template-columns: auto 1fr;
    gap: 10px;
    align-items: center;
}

.files, .ranks {
    display: flex;
    justify-content: space-around;
    font-weight: bold;
    color: #333;
    font-size: 14px;
}

.files {
    grid-column: 2;
}

.ranks {
    grid-row: 1;
    flex-direction: column;
    padding: 0 5px;
}

.side-panel {
    flex: 0 0 300px;
    display: flex;
    flex-direction: column;
    gap: 30px;
    min-width: 280px;
}

.captured-section,
.history-section {
    border: 2px solid #e0e0e0;
    border-radius: 8px;
    padding: 15px;
    background: #fafafa;
}

.captured-section h3,
.history-section h3 {
    font-size: 16px;
    margin-bottom: 12px;
    color: #333;
    border-bottom: 2px solid #667eea;
    padding-bottom: 8px;
}

.captured-pieces {
    display: flex;
    flex-direction: column;
    gap: 12px;
}

.captured-white,
.captured-black {
    background: white;
    padding: 10px;
    border-radius: 6px;
    border-left: 4px solid #667eea;
}

.captured-label {
    font-size: 12px;
    font-weight: 600;
    color: #666;
    margin-bottom: 8px;
    text-transform: uppercase;
}

.pieces-list {
    display: flex;
    gap: 4px;
    flex-wrap: wrap;
    min-height: 24px;
}

.piece-item {
    font-size: 1.2em;
    padding: 2px 4px;
}

.move-history-list {
    background: white;
    border-radius: 6px;
    max-height: 400px;
    overflow-y: auto;
    padding: 10px;
    font-size: 13px;
}

.move-item {
    padding: 6px 8px;
    margin-bottom: 4px;
    background: #f5f5f5;
    border-left: 3px solid #667eea;
    border-radius: 3px;
    font-family: 'Courier New', monospace;
    color: #333;
}

.move-item.last {
    background: #e3f2fd;
    border-left-color: #2196f3;
    font-weight: 600;
}

.empty-message {
    text-align: center;
    color: #999;
    font-size: 12px;
    padding: 20px;
}

.controls-section {
    display: flex;
    flex-direction: column;
    gap: 10px;
}

.btn {
    padding: 12px 16px;
    border: none;
    border-radius: 6px;
    font-size: 14px;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.3s ease;
    text-transform: uppercase;
    letter-spacing: 0.5px;
}

.btn-undo {
    background: #ffa726;
    color: white;
}

.btn-undo:hover:not(:disabled) {
    background: #fb8c00;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(255, 167, 38, 0.4);
}

.btn-undo:disabled {
    background: #ccc;
    cursor: not-allowed;
    opacity: 0.6;
}

.btn-restart {
    background: #66bb6a;
    color: white;
}

.btn-restart:hover {
    background: #43a047;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(102, 187, 106, 0.4);
}

.btn-reset {
    background: #ef5350;
    color: white;
}

.btn-reset:hover {
    background: #e53935;
    transform: translateY(-2px);
    box-shadow: 0 4px 12px rgba(239, 83, 80, 0.4);
}

.selection-info {
    background: #f5f5f5;
    padding: 12px 30px;
    text-align: center;
    border-top: 1px solid #e0e0e0;
    color: #666;
    font-size: 13px;
}

.selection-info p {
    margin: 0;
}

.validation-message {
    position: fixed;
    top: 20px;
    right: 20px;
    padding: 12px 20px;
    border-radius: 6px;
    display: none;
    animation: slideIn 0.3s ease;
    z-index: 1000;
    max-width: 300px;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
}

.validation-message.show {
    display: block;
}

.validation-message.success {
    background: #4caf50;
    color: white;
}

.validation-message.error {
    background: #f44336;
    color: white;
}

.validation-message.info {
    background: #2196f3;
    color: white;
}

@keyframes slideIn {
    from {
        transform: translateX(400px);
        opacity: 0;
    }
    to {
        transform: translateX(0);
        opacity: 1;
    }
}

@media (max-width: 768px) {
    .game-content {
        flex-direction: column;
    }

    .side-panel {
        flex: 1;
        max-width: 100%;
    }

    .game-info {
        flex-direction: column;
        gap: 10px;
    }

    .board-coordinates {
        grid-template-columns: auto 1fr;
    }
}
`;

// Generate JavaScript file
const jsContent = `class ChessGame {
    constructor() {
        this.boardElement = document.getElementById('chessboard');
        this.undoBtn = document.getElementById('undoBtn');
        this.restartBtn = document.getElementById('restartBtn');
        this.resetBtn = document.getElementById('resetBtn');
        this.moveHistoryElement = document.getElementById('moveHistory');
        this.currentTurnElement = document.getElementById('currentTurn');
        this.gameStatusElement = document.getElementById('gameStatus');
        this.selectionText = document.getElementById('selectionText');
        this.validationMsg = document.getElementById('validationMessage');
        
        this.initializeBoard();
        this.attachEventListeners();
        this.updateDisplay();
    }

    initializeBoard() {
        this.board = Array(8).fill(null).map(() => Array(8).fill(null));
        this.currentPlayer = 'white';
        this.selectedSquare = null;
        this.moveHistory = [];
        this.capturedPieces = { white: [], black: [] };
        this.validMoves = [];
        
        this.setupStartPosition();
        this.renderBoard();
    }

    setupStartPosition() {
        const pieces = {
            'r': 'rook', 'n': 'knight', 'b': 'bishop',
            'q': 'queen', 'k': 'king', 'p': 'pawn'
        };

        // Black pieces (top)
        this.board[0] = ['r', 'n', 'b', 'q', 'k', 'b', 'n', 'r'].map(p => ({ type: p, color: 'black' }));
        this.board[1] = Array(8).fill({ type: 'p', color: 'black' });

        // White pieces (bottom)
        this.board[6] = Array(8).fill({ type: 'p', color: 'white' });
        this.board[7] = ['r', 'n', 'b', 'q', 'k', 'b', 'n', 'r'].map(p => ({ type: p, color: 'white' }));
    }

    renderBoard() {
        this.boardElement.innerHTML = '';
        
        for (let row = 0; row < 8; row++) {
            for (let col = 0; col < 8; col++) {
                const square = document.createElement('div');
                square.className = 'square';
                square.classList.add((row + col) % 2 === 0 ? 'light' : 'dark');
                square.dataset.row = row;
                square.dataset.col = col;

                const piece = this.board[row][col];
                if (piece) {
                    const pieceEl = document.createElement('div');
                    pieceEl.className = 'piece';
                    pieceEl.textContent = this.getPieceSymbol(piece.type, piece.color);
                    pieceEl.draggable = true;
                    pieceEl.dataset.row = row;
                    pieceEl.dataset.col = col;
                    square.appendChild(pieceEl);
                } else {
                    square.classList.add('empty');
                }

                square.addEventListener('click', (e) => this.handleSquareClick(row, col, e));
                square.addEventListener('dragover', (e) => this.handleDragOver(e, row, col));
                square.addEventListener('drop', (e) => this.handleDrop(e, row, col));
                square.addEventListener('dragenter', (e) => this.handleDragEnter(e, row, col));
                square.addEventListener('dragleave', (e) => this.handleDragLeave(e, row, col));

                if (piece) {
                    const pieceEl = square.querySelector('.piece');
                    pieceEl.addEventListener('dragstart', (e) => this.handleDragStart(e, row, col));
                    pieceEl.addEventListener('dragend', (e) => this.handleDragEnd(e));
                }

                this.boardElement.appendChild(square);
            }
        }

        this.updateHighlights();
    }

    handleSquareClick(row, col, event) {
        const piece = this.board[row][col];
        
        // If clicking on a valid move, execute it
        if (this.validMoves.some(m => m.row === row && m.col === col)) {
            this.executeMove(this.selectedSquare.row, this.selectedSquare.col, row, col);
            return;
        }

        // If clicking on own piece, select it
        if (piece && piece.color === this.currentPlayer) {
            this.selectedSquare = { row, col };
            this.calculateValidMoves(row, col);
            this.selectionText.textContent = \`Selected: \${this.getPieceSymbol(piece.type, piece.color)} at \${this.getSquareName(row, col)}\`;
            this.updateHighlights();
            return;
        }

        // Clear selection if clicking elsewhere
        this.selectedSquare = null;
        this.validMoves = [];
        this.selectionText.textContent = 'Click a piece to select it';
        this.updateHighlights();
    }

    handleDragStart(event, row, col) {
        const piece = this.board[row][col];
        if (piece && piece.color === this.currentPlayer) {
            event.dataTransfer.effectAllowed = 'move';
            this.selectedSquare = { row, col };
            this.calculateValidMoves(row, col);
            event.target.classList.add('dragging');
        }
    }

    handleDragEnd(event) {
        event.target.classList.remove('dragging');
    }

    handleDragOver(event, row, col) {
        event.preventDefault();
        event.dataTransfer.dropEffect = 'move';
    }

    handleDragEnter(event, row, col) {
        const square = this.getSquareElement(row, col);
        if (this.validMoves.some(m => m.row === row && m.col === col)) {
            square.classList.add('valid-move');
        }
    }

    handleDragLeave(event, row, col) {
        const square = this.getSquareElement(row, col);
        square.classList.remove('valid-move');
    }

    handleDrop(event, toRow, toCol) {
        event.preventDefault();
        
        if (this.selectedSquare && 
            this.validMoves.some(m => m.row === toRow && m.col === toCol)) {
            this.executeMove(this.selectedSquare.row, this.selectedSquare.col, toRow, toCol);
        } else {
            this.showValidationMessage('Invalid move', 'error');
        }
    }

    calculateValidMoves(row, col) {
        this.validMoves = [];
        const piece = this.board[row][col];
        if (!piece) return;

        const moves = [];

        switch (piece.type) {
            case 'p': // Pawn
                const direction = piece.color === 'white' ? -1 : 1;
                const startRow = piece.color === 'white' ? 6 : 1;
                
                // Forward move
                if (this.isValidPosition(row + direction, col) && !this.board[row + direction][col]) {
                    moves.push({ row: row + direction, col });
                    
                    // Double move from start
                    if (row === startRow && !this.board[row + 2 * direction][col]) {
                        moves.push({ row: row + 2 * direction, col });
                    }
                }
                
                // Captures
                for (let c of [-1, 1]) {
                    const nr = row + direction, nc = col + c;
                    if (this.isValidPosition(nr, nc) && this.board[nr][nc] && 
                        this.board[nr][nc].color !== piece.color) {
                        moves.push({ row: nr, col: nc });
                    }
                }
                break;

            case 'r': // Rook
                moves.push(...this.getLineMoves(row, col));
                break;

            case 'n': // Knight
                const knightMoves = [
                    [-2, -1], [-2, 1], [-1, -2], [-1, 2],
                    [1, -2], [1, 2], [2, -1], [2, 1]
                ];
                for (let [dr, dc] of knightMoves) {
                    const nr = row + dr, nc = col + dc;
                    if (this.isValidPosition(nr, nc) && 
                        (!this.board[nr][nc] || this.board[nr][nc].color !== piece.color)) {
                        moves.push({ row: nr, col: nc });
                    }
                }
                break;

            case 'b': // Bishop
                moves.push(...this.getDiagonalMoves(row, col));
                break;

            case 'q': // Queen
                moves.push(...this.getLineMoves(row, col));
                moves.push(...this.getDiagonalMoves(row, col));
                break;

            case 'k': // King
                for (let dr = -1; dr <= 1; dr++) {
                    for (let dc = -1; dc <= 1; dc++) {
                        if (dr === 0 && dc === 0) continue;
                        const nr = row + dr, nc = col + dc;
                        if (this.isValidPosition(nr, nc) && 
                            (!this.board[nr][nc] || this.board[nr][nc].color !== piece.color)) {
                            moves.push({ row: nr, col: nc });
                        }
                    }
                }
                break;
        }

        this.validMoves = moves;
    }

    getLineMoves(row, col) {
        const moves = [];
        const directions = [[0, 1], [0, -1], [1, 0], [-1, 0]];
        
        for (let [dr, dc] of directions) {
            for (let i = 1; i < 8; i++) {
                const nr = row + dr * i, nc = col + dc * i;
                if (!this.isValidPosition(nr, nc)) break;
                
                if (!this.board[nr][nc]) {
                    moves.push({ row: nr, col: nc });
                } else {
                    if (this.board[nr][nc].color !== this.board[row][col].color) {
                        moves.push({ row: nr, col: nc });
                    }
                    break;
                }
            }
        }
        return moves;
    }

    getDiagonalMoves(row, col) {
        const moves = [];
        const directions = [[1, 1], [1, -1], [-1, 1], [-1, -1]];
        
        for (let [dr, dc] of directions) {
            for (let i = 1; i < 8; i++) {
                const nr = row + dr * i, nc = col + dc * i;
                if (!this.isValidPosition(nr, nc)) break;
                
                if (!this.board[nr][nc]) {
                    moves.push({ row: nr, col: nc });
                } else {
                    if (this.board[nr][nc].color !== this.board[row][col].color) {
                        moves.push({ row: nr, col: nc });
                    }
                    break;
                }
            }
        }
        return moves;
    }

    executeMove(fromRow, fromCol, toRow, toCol) {
        const piece = this.board[fromRow][fromCol];
        const target = this.board[toRow][toCol];

        // Validate move
        if (!this.validMoves.some(m => m.row === toRow && m.col === toCol)) {
            this.showValidationMessage('Invalid move', 'error');
            return;
        }

        // Capture piece if present
        if (target) {
            this.capturedPieces[piece.color].push(target);
            this.showValidationMessage(\`Captured \${this.getPieceSymbol(target.type, target.color)}\`, 'success');
        }

        // Move piece
        this.board[toRow][toCol] = piece;
        this.board[fromRow][fromCol] = null;

        // Record move
        const moveName = \`\${this.getSquareName(fromRow, fromCol)}\${this.getSquareName(toRow, toCol)}\`;
        this.moveHistory.push({
            move: moveName,
            piece: piece.type,
            from: { row: fromRow, col: fromCol },
            to: { row: toRow, col: toCol },
            captured: target
        });

        // Switch player
        this.currentPlayer = this.currentPlayer === 'white' ? 'black' : 'white';
        this.selectedSquare = null;
        this.validMoves = [];

        this.updateDisplay();
        this.renderBoard();
    }

    undoLastMove() {
        if (this.moveHistory.length === 0) {
            this.showValidationMessage('No moves to undo', 'info');
            return;
        }

        const lastMove = this.moveHistory.pop();
        const piece = this.board[lastMove.to.row][lastMove.to.col];

        // Move piece back
        this.board[lastMove.from.row][lastMove.from.col] = piece;
        this.board[lastMove.to.row][lastMove.to.col] = null;

        // Restore captured piece
        if (lastMove.captured) {
            this.board[lastMove.to.row][lastMove.to.col] = lastMove.captured;
            this.capturedPieces[piece.color] = this.capturedPieces[piece.color].filter(
                p => p !== lastMove.captured
            );
        }

        // Switch player back
        this.currentPlayer = this.currentPlayer === 'white' ? 'black' : 'white';

        this.showValidationMessage('Move undone', 'success');
        this.updateDisplay();
        this.renderBoard();
    }

    restartGame() {
        this.initializeBoard();
        this.showValidationMessage('Game restarted', 'info');
        this.updateDisplay();
    }

    resetBoard() {
        this.board = Array(8).fill(null).map(() => Array(8).fill(null));
        this.renderBoard();
        this.showValidationMessage('Board cleared', 'info');
    }

    updateDisplay() {
        // Update turn
        this.currentTurnElement.textContent = this.currentPlayer.charAt(0).toUpperCase() + this.currentPlayer.slice(1);
        this.currentTurnElement.className = 'value ' + this.currentPlayer;

        // Update move history
        this.updateMoveHistory();

        // Update captured pieces
        this.updateCapturedPieces();

        // Update undo button
        this.undoBtn.disabled = this.moveHistory.length === 0;
    }

    updateMoveHistory() {
        if (this.moveHistory.length === 0) {
            this.moveHistoryElement.innerHTML = '<p class="empty-message">No moves yet</p>';
            return;
        }

        this.moveHistoryElement.innerHTML = this.moveHistory.map((m, idx) => 
            \`<div class="move-item \${idx === this.moveHistory.length - 1 ? 'last' : ''}">
                \${Math.floor(idx / 2) + 1}. \${m.move} (\${m.piece})\${m.captured ? ' x' : ''}
            </div>\`
        ).join('');
    }

    updateCapturedPieces() {
        const whiteCaptured = document.getElementById('capturedWhite');
        const blackCaptured = document.getElementById('capturedBlack');

        whiteCaptured.innerHTML = this.capturedPieces.white.length > 0
            ? this.capturedPieces.white.map(p => 
                \`<span class="piece-item">\${this.getPieceSymbol(p.type, p.color)}</span>\`
              ).join('')
            : '<span class="empty-message">-</span>';

        blackCaptured.innerHTML = this.capturedPieces.black.length > 0
            ? this.capturedPieces.black.map(p => 
                \`<span class="piece-item">\${this.getPieceSymbol(p.type, p.color)}</span>\`
              ).join('')
            : '<span class="empty-message">-</span>';
    }

    updateHighlights() {
        const squares = document.querySelectorAll('.square');
        squares.forEach(sq => {
            sq.classList.remove('selected', 'valid-move', 'invalid-move');
        });

        if (this.selectedSquare) {
            const sq = this.getSquareElement(this.selectedSquare.row, this.selectedSquare.col);
            sq.classList.add('selected');

            this.validMoves.forEach(m => {
                const moveSq = this.getSquareElement(m.row, m.col);
                moveSq.classList.add('valid-move');
            });
        }
    }

    getSquareElement(row, col) {
        return document.querySelector(\`[data-row="\${row}"][data-col="\${